// 将 assets/formats 路径下的模型 形成配置
export const newMultModels = [
  // FBX 格式模型
  {
    name: 'boat1 (FBX)',
    type: 'fbx',
    path: '/assets/formats/boat1.fbx',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'building1 (FBX)',
    type: 'fbx',
    path: '/assets/formats/building1.fbx',
    position: [0, 0, 0],
    scale: [0.005, 0.005, 0.005],
  },
  {
    name: 'building2 (FBX)',
    type: 'fbx',
    path: '/assets/formats/building2.fbx',
    position: [0, 0, 0],
    scale: [0.005, 0.005, 0.005],
  },
  {
    name: 'container1 (FBX)',
    type: 'fbx',
    path: '/assets/formats/container1.fbx',
    position: [0, 0, 0],
    scale: [0.01, 0.01, 0.01],
  },
  {
    name: 'container2 (FBX)',
    type: 'fbx',
    path: '/assets/formats/container2.fbx',
    position: [0, 0, 0],
    scale: [0.01, 0.01, 0.01],
  },
  {
    name: 'container3 (FBX)',
    type: 'fbx',
    path: '/assets/formats/container3.fbx',
    position: [0, 0, 0],
    scale: [0.01, 0.01, 0.01],
  },
  {
    name: 'container4 (FBX)',
    type: 'fbx',
    path: '/assets/formats/container4.fbx',
    position: [0, 0, 0],
    scale: [0.01, 0.01, 0.01],
  },
  {
    name: 'crane1 (FBX)',
    type: 'fbx',
    path: '/assets/formats/crane1.fbx',
    position: [0, 0, 0],
    scale: [0.005, 0.005, 0.005],
  },
  {
    name: 'crane2 (FBX)',
    type: 'fbx',
    path: '/assets/formats/crane2.fbx',
    position: [0, 0, 0],
    scale: [0.005, 0.005, 0.005],
  },
  {
    name: 'fence (FBX)',
    type: 'fbx',
    path: '/assets/formats/fence.fbx',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'lift (FBX)',
    type: 'fbx',
    path: '/assets/formats/lift.fbx',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'palette (FBX)',
    type: 'fbx',
    path: '/assets/formats/palette.fbx',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
//   {
//     name: 'port (FBX)',
//     type: 'fbx',
//     path: '/assets/formats/port.fbx',
//     position: [0, 0, 0],
//     scale: [0.05, 0.05, 0.05],
//   },
//   {
//     name: 'ship (FBX)',
//     type: 'fbx',
//     path: '/assets/formats/ship.fbx',
//     position: [0, 0, 0],
//     scale: [0.05, 0.05, 0.05],
//   },
  {
    name: 'truck1 (FBX)',
    type: 'fbx',
    path: '/assets/formats/truck1.fbx',
    position: [0, 0, 0],
    scale: [0.005, 0.005, 0.005],

  },
  {
    name: 'truck2 (FBX)',
    type: 'fbx',
    path: '/assets/formats/truck2.fbx',
    position: [0, 0, 0],
    scale: [0.005, 0.005, 0.005],
  },
  
  // OBJ+MTL 格式模型
  {    name: 'boat1 (OBJ)',    type: 'obj_mtl',    path: '/assets/formats/boat1.obj',    mtlPath: '/assets/formats/boat1.mtl',    position: [0, 0, 0],    scale: [0.05, 0.05, 0.05],  },
  {
    name: 'building1 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/building1.obj',
    mtlPath: '/assets/formats/building1.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'building2 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/building2.obj',
    mtlPath: '/assets/formats/building2.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'container1 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/container1.obj',
    mtlPath: '/assets/formats/container1.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'container2 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/container2.obj',
    mtlPath: '/assets/formats/container2.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'container3 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/container3.obj',
    mtlPath: '/assets/formats/container3.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'container4 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/container4.obj',
    mtlPath: '/assets/formats/container4.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'crane1 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/crane1.obj',
    mtlPath: '/assets/formats/crane1.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'crane2 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/crane2.obj',
    mtlPath: '/assets/formats/crane2.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'fence (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/fence.obj',
    mtlPath: '/assets/formats/fence.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'lift (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/lift.obj',
    mtlPath: '/assets/formats/lift.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'palette (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/palette.obj',
    mtlPath: '/assets/formats/palette.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
//   {
//     name: 'port (OBJ)',
//     type: 'obj_mtl',
//     path: '/assets/formats/port.obj',
//     mtlPath: '/assets/formats/port.mtl',
//     position: [0, 0, 0],
//     scale: [0.05, 0.05, 0.05],
//   },
  {
    name: 'ship (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/ship.obj',
    mtlPath: '/assets/formats/ship.mtl',
    position: [0, 0, 0],
    scale: [0.01, 0.01, 0.01],
  },
  {
    name: 'truck1 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/truck1.obj',
    mtlPath: '/assets/formats/truck1.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
  {
    name: 'truck2 (OBJ)',
    type: 'obj_mtl',
    path: '/assets/formats/truck2.obj',
    mtlPath: '/assets/formats/truck2.mtl',
    position: [0, 0, 0],
    scale: [0.05, 0.05, 0.05],
  },
]